# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDYbQKZAuiykEb-BSLfa6IZ3Rx_-8f7S
"""

import pandas as pd
ps = pd.read_csv("/content/statsfinal1.csv")
ps

max_sale_row = ps[ps['S-P1'] == ps['S-P1'].max()]

# Print the result
print("The highest peak in sales occurred on:")
print(max_sale_row)

max_sale_row = ps[ps['S-P2'] == ps['S-P2'].max()]

# Print the result
print("The highest peak in sales occurred on:")
print(max_sale_row)

max_sale_row = ps[ps['S-P3'] == ps['S-P3'].max()]

# Print the result
print("The highest peak in sales occurred on:")
print(max_sale_row)

max_sale_row = ps[ps['S-P4'] == ps['S-P4'].max()]

# Print the result
print("The highest peak in sales occurred on:")
print(max_sale_row)

df = pd.read_csv("/content/statsfinal1.csv")
max_sale_row1 = df[df['S-P1'] == df['S-P1'].max()]
max_sale_row2 = df[df['S-P2'] == df['S-P2'].max()]
max_sale_row3 = df[df['S-P3'] == df['S-P3'].max()]
max_sale_row4 = df[df['S-P4'] == df['S-P4'].max()]


product_name1 = max_sale_row['Q-P1'].values[0]
peak_sales1 = max_sale_row['S-P1'].values[0]
product_name2 = max_sale_row['Q-P2'].values[0]
peak_sales2 = max_sale_row['S-P2'].values[0]
product_name3 = max_sale_row['Q-P3'].values[0]
peak_sales3 = max_sale_row['S-P3'].values[0]
product_name4 = max_sale_row['Q-P4'].values[0]
peak_sales4 = max_sale_row['S-P4'].values[0]

# Print the result
print(f"The product with the highest peak sales is '{product_name1}' with {peak_sales1} units sold.")
print(f"The product with the highest peak sales is '{product_name2}' with {peak_sales2} units sold.")
print(f"The product with the highest peak sales is '{product_name3}' with {peak_sales3} units sold.")
print(f"The product with the highest peak sales is '{product_name4}' with {peak_sales4} units sold.")

customer_preferences = df.groupby('Q-P1').agg({
    'S-P1': 'sum',
    'S-P2': 'mean',
    'S-P3': 'max',
    'S-P4': 'min'
}).reset_index()


customer_preferences['TotalPreference'] = customer_preferences[['S-P1', 'S-P2', 'S-P3','S-P4']].sum(axis=1)
customer_preferences = customer_preferences.sort_values(by='TotalPreference', ascending=False)

print("Customer preferences:")
print(customer_preferences)

customer_preferences = df.groupby('Q-P2').agg({
    'S-P1': 'sum',
    'S-P2': 'mean',
    'S-P3': 'max',
    'S-P4': 'min'
}).reset_index()


customer_preferences['TotalPreference'] = customer_preferences[['S-P1', 'S-P2', 'S-P3','S-P4']].sum(axis=1)
customer_preferences = customer_preferences.sort_values(by='TotalPreference', ascending=False)

print("Customer preferences:")
print(customer_preferences)

customer_preferences = df.groupby('Q-P3').agg({
    'S-P1': 'sum',
    'S-P2': 'mean',
    'S-P3': 'max',
    'S-P4': 'min'
}).reset_index()


customer_preferences['TotalPreference'] = customer_preferences[['S-P1', 'S-P2', 'S-P3','S-P4']].sum(axis=1)
customer_preferences = customer_preferences.sort_values(by='TotalPreference', ascending=False)

print("Customer preferences:")
print(customer_preferences)

customer_preferences = df.groupby('Q-P4').agg({
    'S-P1': 'sum',
    'S-P2': 'mean',
    'S-P3': 'max',
    'S-P4': 'min'
}).reset_index()


customer_preferences['TotalPreference'] = customer_preferences[['S-P1', 'S-P2', 'S-P3','S-P4']].sum(axis=1)
customer_preferences = customer_preferences.sort_values(by='TotalPreference', ascending=False)

print("Customer preferences:")
print(customer_preferences)